function [SAMcov,channelindex,hpfreq,lpfreq] = nut_read_SAMcov(filename)
% [SAMcov,channelindex,hpfreq,lpfreq] = nut_read_SAMcov(filename)
% 
% Reads SAM covariance from a .cov file (generated by CTF's SAMcov)

fid=fopen(filename,'r','b');
identity = transpose(fread(fid,8,'uint8=>char'));
if(~strcmp(identity,'SAMCOVAR'))
    error('This doesn''t look like a SAM COVAR file.');
end
vers = fread(fid,1,'int32');
setname = fread(fid,256,'uint8=>char');
specname = fread(fid,256,'uint8=>char');

numchans = fread(fid,1,'int32');
hpfreq = fread(fid,1,'double');
lpfreq = fread(fid,1,'double');
bwfreq = fread(fid,1,'double');
numsegments = fread(fid,1,'int32');
numsamples = fread(fid,1,'int32');
covtype = fread(fid,1,'int32');
padbytes1 = fread(fid,1,'int32');

channelindex = fread(fid,numchans,'int32');
SAMcov = fread(fid,[numchans,numchans],'double');
% SAMcov = reshape(SAMcov,numchans,numchans);

fclose(fid);

% [meshz,meshy,meshx]=ndgrid(zstart:params.stepsize:zend,ystart:params.stepsize:yend,xstart:params.stepsize:xend);
% coords = [meshx(:) meshy(:) meshz(:)];

